# Generated by Django 2.2.12 on 2020-07-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(max_length=200, unique=True)),
                ('key', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
