# Generated by Django 2.2.12 on 2020-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesaions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_slug', models.CharField(max_length=255, unique=True)),
                ('key', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Links_key',
        ),
    ]
