# Generated by Django 2.2.12 on 2020-07-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_chat', '0002_auto_20200727_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sesaions',
            new_name='Session',
        ),
    ]
