# Generated by Django 2.2.12 on 2020-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_chat', '0003_auto_20200728_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='link_slug',
            field=models.CharField(max_length=255),
        ),
    ]
