# Generated by Django 2.2.12 on 2020-08-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_chat', '0004_auto_20200728_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_slug', models.CharField(max_length=255, unique=True)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('chat', models.CharField(max_length=1000)),
            ],
        ),
    ]
