# Generated by Django 2.2.12 on 2020-08-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_chat', '0005_chat_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_table',
            name='link_slug',
            field=models.CharField(max_length=255),
        ),
    ]
