# Generated by Django 2.2.12 on 2020-08-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_chat', '0006_auto_20200809_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_table',
            name='read',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='chat_table',
            name='uuid',
            field=models.CharField(max_length=255),
        ),
    ]
