# Generated by Django 2.2.12 on 2020-08-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_chat', '0011_auto_20200812_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_table',
            name='chat',
            field=models.CharField(default='_', max_length=1000),
        ),
    ]
